[base]
pidfile = "/tmp/comet.pid"
logfile = "/Users/AT/go/src/im/logs/comet/comet.log"
serverId = 1
certPath = "/etc/letsencrypt/live/texixi.com-0002/fullchain.pem"
keyPath = "/etc/letsencrypt/live/texixi.com-0002/privkey.pem"

[websocket]
bind = "0.0.0.0:8911"


[[rpcLogicAddrs]]
key = 1
addr = "tcp@0.0.0.0:6923"

[[rpcPushAddrs]]
key = 1
addr = "tcp@0.0.0.0:6912"




[bucket]

num = 256
channel = 1024
room = 1024
svrProto = 80
routineAmount = 32
routineSize = 20



