[base]
pidfile = "/tmp/comet.pid"
logfile = "/Users/AT/go/src/im/logs/comet/comet.log"
rpcLogicAddr = "tcp@0.0.0.0:6923"


[websocket]
bind = "0.0.0.0:7911"



[bucket]

num = "256"
channel = "1024"
room = "1024"
svrProto = "80"


