[base]
pidfile = "/tmp/logic.pid"

RedisAddr = "localhost:6379"
redisPw = ""
RPCAddrs = "tcp@localhost:6923"

certPath = "/etc/letsencrypt/live/texixi.com-0002/fullchain.pem"
keyPath = "/etc/letsencrypt/live/texixi.com-0002/privkey.pem"






